package br.com.ifba.instrumento.view;

import br.com.ifba.instrumento.controller.InstrumentoIController;
import br.com.ifba.instrumento.entity.InstrumentoMetal;

/**
 *
 * @author anriu
 */
public class CadastroInstrumentoMetal extends javax.swing.JFrame {

    private InstrumentoMetal instrumento;
    private br.com.ifba.instrumento.controller.InstrumentoIController instrumentoController;
    
    /**
     * Creates new form CadstroMetal
     */
    public CadastroInstrumentoMetal(InstrumentoIController instrumentoController) {
        initComponents();
        
        setDefaultCloseOperation(
              javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );

        this.instrumentoController = instrumentoController;

        this.instrumento = new InstrumentoMetal();
    }

    public CadastroInstrumentoMetal(InstrumentoMetal instrumento, InstrumentoIController instrumentoController) {

        initComponents();

        setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );

        this.instrumento = instrumento;
        this.instrumentoController = instrumentoController;


        txtNome.setText(instrumento.getNome());
        txtNumSerie.setText(instrumento.getNumSerie());
        txtMarca.setText(instrumento.getMarca());
        txtModelo.setText(instrumento.getModelo());

        cbEstado.setSelectedItem(instrumento.getEstadoConservacao());
        cbAfinacao.setSelectedItem(instrumento.getAfinacao());
        spnQuantidadePistons.setValue(instrumento.getQtdPistoes());
        
        if (instrumento.isPossuiRotor()) {
            cbRotor.setSelectedItem("Sim");
        } else {
            cbRotor.setSelectedItem("Não");
        }
 
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblnumSerie = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblEstadoDeConservacao = new javax.swing.JLabel();
        lblAfinacao = new javax.swing.JLabel();
        lblPalheta = new javax.swing.JLabel();
        txtNumSerie = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        bntSalvar = new javax.swing.JButton();
        cbAfinacao = new javax.swing.JComboBox<>();
        spnQuantidadePistons = new javax.swing.JSpinner();
        lblPalheta1 = new javax.swing.JLabel();
        cbRotor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(3, 28, 48));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome do Instrumento:");

        lblnumSerie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblnumSerie.setForeground(new java.awt.Color(255, 255, 255));
        lblnumSerie.setText("Número de Série:");

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Marca:");

        lblModelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(255, 255, 255));
        lblModelo.setText("Modelo:");

        lblEstadoDeConservacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstadoDeConservacao.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoDeConservacao.setText("Estado de Conservação");

        lblAfinacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAfinacao.setForeground(new java.awt.Color(255, 255, 255));
        lblAfinacao.setText("Afinação:");

        lblPalheta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPalheta.setForeground(new java.awt.Color(255, 255, 255));
        lblPalheta.setText("Quantidade de Pistons:");

        txtNumSerie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtMarca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtModelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Funcionando", "Quebrado" }));

        bntSalvar.setText("Salvar");
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });

        cbAfinacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dó", "Si Bemol", "Mi Bemol" }));

        spnQuantidadePistons.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 1));

        lblPalheta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPalheta1.setForeground(new java.awt.Color(255, 255, 255));
        lblPalheta1.setText("Possui Rotor:");

        cbRotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblNome)
                        .addGap(19, 19, 19)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblnumSerie)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblMarca)
                        .addGap(18, 18, 18)
                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblModelo)
                        .addGap(18, 18, 18)
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblEstadoDeConservacao)
                        .addGap(18, 18, 18)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPalheta)
                            .addComponent(lblAfinacao)
                            .addComponent(lblPalheta1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnQuantidadePistons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAfinacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbRotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblNome))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblnumSerie))
                    .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblMarca))
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblModelo))
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoDeConservacao)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAfinacao)
                    .addComponent(cbAfinacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnQuantidadePistons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPalheta))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPalheta1)
                    .addComponent(cbRotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(bntSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        // TODO add your handling code here:

        
        instrumento.setTipo("Metal");
        instrumento.setNome(txtNome.getText().trim());
        instrumento.setNumSerie(txtNumSerie.getText().trim());
        instrumento.setMarca(txtMarca.getText().trim());
        instrumento.setModelo(txtModelo.getText().trim());
        instrumento.setEstadoConservacao(cbEstado.getSelectedItem().toString());
        instrumento.setAfinacao(cbAfinacao.getSelectedItem().toString());
        
        
        
        instrumento.setQtdPistoes((Integer) spnQuantidadePistons.getValue());
        
        if(cbRotor.getSelectedItem().toString().equals("Sim")){
           instrumento.setPossuiRotor(true); 
        }else{
           instrumento.setPossuiRotor(false); 
        }
  
        
        if (instrumento.getId() == null) {
            instrumentoController.save(instrumento);
        } else {
            instrumentoController.update(instrumento);
        }

        this.dispose();

    }//GEN-LAST:event_bntSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroInstrumentoMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroInstrumentoMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroInstrumentoMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroInstrumentoMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalvar;
    private javax.swing.JComboBox<String> cbAfinacao;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbRotor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAfinacao;
    private javax.swing.JLabel lblEstadoDeConservacao;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPalheta;
    private javax.swing.JLabel lblPalheta1;
    private javax.swing.JLabel lblnumSerie;
    private javax.swing.JSpinner spnQuantidadePistons;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumSerie;
    // End of variables declaration//GEN-END:variables
}
