package br.com.ifba.instrumento.view;
import br.com.ifba.instrumento.controller.InstrumentoIController;
import br.com.ifba.instrumento.entity.InstrumentoMetal;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author anriu
 */
@Component
@Scope("prototype")

public class ExibirDetalhesMetal extends javax.swing.JFrame {

    private final InstrumentoMetal instrumento;
    /**
     * Creates new form ExibirDetalhesMetal
     */
    
    public ExibirDetalhesMetal(InstrumentoMetal instrumento) {
        initComponents();

        setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );

        this.instrumento = instrumento;
 

        carregarDadosInstrumento();   
    }
    
    private void carregarDadosInstrumento() {

        txtNome.setText(instrumento.getNome());
        txtNumSerie.setText(instrumento.getNumSerie());
        txtMarca.setText(instrumento.getMarca());
        txtModelo.setText(instrumento.getModelo());

        txtConservacao.setText(
                instrumento.getEstadoConservacao()
        );

        txtAfinacao.setText(
                instrumento.getTonalidade().getDescricao()
        );

        txtQuantidadePistons.setText(
                String.valueOf(instrumento.getQtdPistoes())
        );


        if (instrumento.isPossuiRotor()) {
            txtRotor.setText("Possui rotor");
        } else {
            txtRotor.setText("Não possui rotor");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblnumSerie = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblEstadoDeConservacao = new javax.swing.JLabel();
        lblAfinacao = new javax.swing.JLabel();
        lblQuantidadePistons = new javax.swing.JLabel();
        lblMusico = new javax.swing.JLabel();
        lblRotor = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtNumSerie = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtAfinacao = new javax.swing.JTextField();
        txtConservacao = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMusicoResponsavel = new javax.swing.JTextField();
        txtQuantidadePistons = new javax.swing.JTextField();
        txtRotor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(3, 28, 48));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome do Instrumento:");

        lblnumSerie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblnumSerie.setForeground(new java.awt.Color(255, 255, 255));
        lblnumSerie.setText("Número de Série:");

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Marca:");

        lblModelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(255, 255, 255));
        lblModelo.setText("Modelo:");

        lblEstadoDeConservacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEstadoDeConservacao.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoDeConservacao.setText("Estado de Conservação");

        lblAfinacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAfinacao.setForeground(new java.awt.Color(255, 255, 255));
        lblAfinacao.setText("Afinação:");

        lblQuantidadePistons.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQuantidadePistons.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantidadePistons.setText("Quantidade de pistons:");

        lblMusico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMusico.setForeground(new java.awt.Color(255, 255, 255));
        lblMusico.setText("Musico Reponsavel:");

        lblRotor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRotor.setForeground(new java.awt.Color(255, 255, 255));
        lblRotor.setText("Rotor");

        txtMarca.setEditable(false);
        txtMarca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtNumSerie.setEditable(false);
        txtNumSerie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtNome.setEditable(false);
        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtAfinacao.setEditable(false);
        txtAfinacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtConservacao.setEditable(false);
        txtConservacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtModelo.setEditable(false);
        txtModelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtMusicoResponsavel.setEditable(false);
        txtMusicoResponsavel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtQuantidadePistons.setEditable(false);
        txtQuantidadePistons.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtRotor.setEditable(false);
        txtRotor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtRotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRotorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRotor)
                        .addGap(26, 26, 26)
                        .addComponent(txtRotor, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMusico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(lblNome))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(lblnumSerie))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(109, 109, 109)
                                    .addComponent(lblMarca))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(lblModelo))
                                .addComponent(lblEstadoDeConservacao)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(lblAfinacao)))
                            .addComponent(lblQuantidadePistons, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAfinacao, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMusicoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidadePistons, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnumSerie)
                            .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarca)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(lblModelo)
                        .addGap(36, 36, 36)
                        .addComponent(lblEstadoDeConservacao)
                        .addGap(33, 33, 33)
                        .addComponent(lblAfinacao))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtAfinacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidadePistons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidadePistons))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRotor))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblMusico))
                    .addComponent(txtMusicoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRotorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirDetalhesMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirDetalhesMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirDetalhesMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirDetalhesMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAfinacao;
    private javax.swing.JLabel lblEstadoDeConservacao;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblMusico;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuantidadePistons;
    private javax.swing.JLabel lblRotor;
    private javax.swing.JLabel lblnumSerie;
    private javax.swing.JTextField txtAfinacao;
    private javax.swing.JTextField txtConservacao;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMusicoResponsavel;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumSerie;
    private javax.swing.JTextField txtQuantidadePistons;
    private javax.swing.JTextField txtRotor;
    // End of variables declaration//GEN-END:variables
}
