/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.instrumento.view;

import br.com.ifba.instrumento.entity.InstrumentoPercussao;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author anriu
 */

@Component
@Scope("prototype")
public class ExibirDetalhesPercussao extends javax.swing.JFrame {

    
    private InstrumentoPercussao instrumento;

    /**
     * Creates new form ExibirDetalhesPercussao
     * @param instrumento
     */
    
    public ExibirDetalhesPercussao(InstrumentoPercussao instrumento) {
        initComponents();
        setDefaultCloseOperation(
              javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );
        
    
        initComponents();

        setDefaultCloseOperation(
                javax.swing.WindowConstants.DISPOSE_ON_CLOSE
        );

        this.instrumento = instrumento;

        carregarDadosInstrumento(); 
    }
    
        private void carregarDadosInstrumento() {

        txtNome.setText(instrumento.getNome());
        txtNumSerie.setText(instrumento.getNumSerie());
        txtMarca.setText(instrumento.getMarca());
        txtModelo.setText(instrumento.getModelo());

        txtConservacao.setText(
                instrumento.getEstadoConservacao()
        );


        if (instrumento.getTipoPele() != null) {
            txtPele.setText(
                    instrumento.getTipoPele()
            );
        } else {
            txtPele.setText(
                    "Não possui pele"
            );
        }


        if (instrumento.getTipoBaqueta() != null) {
            txtBaqueta.setText(
                    instrumento.getTipoBaqueta()
            );
        } else {
            txtBaqueta.setText(
                    "Não possui baqueta"
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblnumSerie = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblEstadoDeConservacao = new javax.swing.JLabel();
        lblPele = new javax.swing.JLabel();
        lblQuantidadePistons = new javax.swing.JLabel();
        lblMusico = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtNumSerie = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtPele = new javax.swing.JTextField();
        txtConservacao = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMusicoResponsavel = new javax.swing.JTextField();
        txtBaqueta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel1.setBackground(new java.awt.Color(3, 28, 48));

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setText("Nome do Instrumento:");

        lblnumSerie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblnumSerie.setForeground(new java.awt.Color(255, 255, 255));
        lblnumSerie.setText("Número de Série:");

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Marca:");

        lblModelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(255, 255, 255));
        lblModelo.setText("Modelo:");

        lblEstadoDeConservacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEstadoDeConservacao.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoDeConservacao.setText("Estado de Conservação");

        lblPele.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPele.setForeground(new java.awt.Color(255, 255, 255));
        lblPele.setText("Tipo de Pele:");

        lblQuantidadePistons.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQuantidadePistons.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantidadePistons.setText("Tipo Baqueta:");

        lblMusico.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMusico.setForeground(new java.awt.Color(255, 255, 255));
        lblMusico.setText("Musico Reponsavel:");

        txtMarca.setEditable(false);
        txtMarca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtNumSerie.setEditable(false);
        txtNumSerie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtNome.setEditable(false);
        txtNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtPele.setEditable(false);
        txtPele.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtConservacao.setEditable(false);
        txtConservacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtModelo.setEditable(false);
        txtModelo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtMusicoResponsavel.setEditable(false);
        txtMusicoResponsavel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        txtBaqueta.setEditable(false);
        txtBaqueta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMusico, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblQuantidadePistons, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblnumSerie)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(lblNome))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEstadoDeConservacao)
                                    .addComponent(lblModelo)))
                            .addComponent(lblMarca))
                        .addGap(5, 5, 5))
                    .addComponent(lblPele, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPele, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMusicoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(txtConservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPele))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnumSerie)
                            .addComponent(txtNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarca)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(lblModelo)
                        .addGap(29, 29, 29)
                        .addComponent(lblEstadoDeConservacao)
                        .addGap(86, 86, 86)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBaqueta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidadePistons))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblMusico))
                    .addComponent(txtMusicoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirDetalhesPercussao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirDetalhesPercussao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirDetalhesPercussao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirDetalhesPercussao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstadoDeConservacao;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblMusico;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPele;
    private javax.swing.JLabel lblQuantidadePistons;
    private javax.swing.JLabel lblnumSerie;
    private javax.swing.JTextField txtBaqueta;
    private javax.swing.JTextField txtConservacao;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMusicoResponsavel;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumSerie;
    private javax.swing.JTextField txtPele;
    // End of variables declaration//GEN-END:variables
}
